// Generated by tools/build-catalogue-import.mjs. Exact reviewed URLs only.
const images = new Set([
  "https://shawfloors.widen.net/content/0vidbuyiqf/jpeg/5e915_00105_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/140hfym69q/jpeg/5e915_00300_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/23og0coqzu/jpeg/5e915_00502_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/2q8imsq0y5/jpeg/5e915_00320_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/3q7mgh8bxn/jpeg/5e915_00150_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/4j3cjtujmi/jpeg/5e915_00401_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/7iptnqrhnq/jpeg/5e915_00702_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/9rn6nkaiuo/jpeg/5e915_00400_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/bqixvdnahi/jpeg/5e915_00108_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/cm3ftpn7ke/jpeg/5e915_00703_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/cxoputhkis/jpeg/5e915_00503_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/dcyocz0wzd/jpeg/5e915_00301_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/edas3wpcls/jpeg/5e915_00104_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/gptycpf16g/jpeg/5e915_00704_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/hya19jejgh/jpeg/5e915_00302_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/i9kstorhix/jpeg/5e915_00701_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/i9sv0902cy/jpeg/5e915_00706_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/iilxxij4ew/jpeg/5e915_00422_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/ilnnetwedh/jpeg/5e915_00103_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/kmmfrroytg/jpeg/5e915_00403_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/l9x5zwiocc/jpeg/5e915_00501_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/lpyxa0lpgk/jpeg/5e915_00107_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/ly0w7zdmgw/jpeg/5e915_00700_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/nko5rgmehf/jpeg/5e915_00800_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/nsukk1azik/jpeg/5e915_00110_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/orfkcppzvw/jpeg/5e915_00801_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/pz5yiqfyrk/jpeg/5e915_00100_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/qsreyezxcw/jpeg/5e915_00402_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/r227pgo6hf/jpeg/5e915_00450_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/sbkaodanxr/jpeg/5e915_00750_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/tupb1k0ltj/jpeg/5e915_00500_main?w=840&h=0&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/u4fvh85bzj/jpeg/5e915_00504_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/v2leakghhm/jpeg/5e915_00106_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/v7fjvmquql/jpeg/5e915_00109_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://shawfloors.widen.net/content/y4tbepwghs/jpeg/5e915_00102_main?w=120&h=120&fmt=jpeg&quality=85&keep=c&crop=true",
  "https://torlys.com/wp-content/uploads/2025/09/Olympic-5-MQLL-550-150x150.jpg"
]);

export const manufacturerImageOrigins = ["https://canada.beaulieucanada.com","https://shawfloors.widen.net","https://torlys.com"];

export function isManufacturerImage(url) {
  return typeof url === 'string' && (images.has(url) || /^https:\/\/canada\.beaulieucanada\.com\/images\/5436-1\/Thumb_Hires-5436-(14312|16855|16986|84199|86583|89056|89823|19204|84294)\.jpg\?_w=600$/.test(url));
}
