"""Validate downloaded images and create content-addressed local WebP assets."""
import hashlib
import json
from pathlib import Path
from PIL import Image, ImageOps

root = Path(__file__).resolve().parent.parent
downloads = json.loads((root / '.image-cache/downloads.json').read_text())
output = root / 'assets/catalogue'
output.mkdir(parents=True, exist_ok=True)
mapping = {}
report = []
for entry in downloads:
    item = dict(entry)
    if entry.get('file'):
        try:
            with Image.open(root / entry['file']) as original:
                image = ImageOps.exif_transpose(original).convert('RGB')
                item['source_width'], item['source_height'] = image.size
                # Never enlarge a thumbnail: preserve its true available detail.
                image.thumbnail((1200, 1200), Image.Resampling.LANCZOS)
                import io
                buffer = io.BytesIO()
                image.save(buffer, format='WEBP', quality=88, method=6)
                content = buffer.getvalue()
                filename = hashlib.sha256(content).hexdigest()[:24] + '.webp'
                (output / filename).write_bytes(content)
                item['local'] = '/assets/catalogue/' + filename
                item['width'], item['height'] = image.size
                item['low_resolution'] = max(image.size) < 600
                item['local_bytes'] = len(content)
                mapping[entry['original']] = item['local']
        except Exception as error:
            item['error'] = str(error)
    item.pop('file', None)
    report.append(item)
(root / 'catalogue-imports/local-image-report.json').write_text(json.dumps(report, indent=2) + '\n')
(root / 'catalogue-image-map.js').write_text(
    '// Generated by tools/prepare-catalogue-images.py. Original URLs remain provenance only.\n'
    'const images = ' + json.dumps(mapping, indent=2) + ';\n'
    'export function catalogueImage(url) { return images[url] || url || null; }\n'
)
print(f'{len(mapping)} local images; {sum(bool(x.get("low_resolution")) for x in report)} below 600 pixels.')
