"""Prepare the reviewed Traced, Rare Vintage and Coastal Driftwood images."""
import hashlib
import io
import json
from pathlib import Path
from PIL import Image, ImageOps

root = Path(__file__).resolve().parent.parent
rows = json.loads((root / 'catalogue-imports/missing-image-sources.json').read_text())
sql = ['-- Fill missing swatches only; preserve existing images and product edits.']
paths = []
for row in rows:
    with Image.open(root / row['file']) as original:
        image = ImageOps.exif_transpose(original).convert('RGB')
        image.thumbnail((1200, 1200), Image.Resampling.LANCZOS)
        output = io.BytesIO()
        image.save(output, 'WEBP', quality=88, method=4)
        content = output.getvalue()
        name = hashlib.sha256(content).hexdigest()[:24] + '.webp'
        (root / 'assets/catalogue' / name).write_bytes(content)
        row.update(local='/assets/catalogue/' + name, width=image.width, height=image.height)
    paths.append(row['local'])
    digest = bytearray(hashlib.sha256(('fcc:catalogue:2026-09-27:' + row['key']).encode()).digest()[:16])
    digest[6] = (digest[6] & 15) | 64
    digest[8] = (digest[8] & 63) | 128
    import uuid
    product_id = str(uuid.UUID(bytes=bytes(digest)))
    quote = lambda value: "'" + value.replace("'", "''") + "'"
    match = "json_extract(value, '$.name') = " + quote(row['name'])
    empty = match + " AND coalesce(json_extract(value, '$.image_id'), '') = '' AND coalesce(json_extract(value, '$.source_image_url'), '') = ''"
    sql.append("UPDATE products SET colours = json_set(colours, '$[' || (SELECT key FROM json_each(products.colours) WHERE " + empty + " LIMIT 1) || '].source_image_url', " + quote(row['local']) + "), version = version + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = " + quote(product_id) + " AND EXISTS (SELECT 1 FROM json_each(products.colours) WHERE " + empty + ");")
(root / 'migrations/0010_missing_product_images.sql').write_text('\n'.join(sql) + '\n')
(root / 'server/local-product-images.js').write_text('// Generated by tools/prepare-missing-images.py. Exact reviewed local files only.\nconst images = new Set(' + json.dumps(paths, indent=2) + ');\nexport const isLocalProductImage = value => images.has(value);\n')
(root / 'catalogue-imports/missing-image-sources.json').write_text(json.dumps(rows, indent=2) + '\n')
print(f'Prepared {len(rows)} missing colour images and migration 0010.')
